spring.application.name=incident-api
spring.datasource.url=jdbc:mysql://localhost:3306/incidentdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.com.shaun.incident_api=DEBUG

